# Generated by Django 3.1.4 on 2020-12-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNPediaAndMe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snpediaandme',
            name='data',
            field=models.JSONField(),
        ),
    ]
