# Generated by Django 3.1.4 on 2020-12-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SNPediaAndMe', '0002_auto_20201218_1257'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SNPediaAndMe',
            new_name='RSID',
        ),
    ]
