# Generated by Django 3.1.4 on 2020-12-18 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SNPediaAndMe', '0003_auto_20201218_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsid',
            name='category',
        ),
    ]
